version: 2
jobs:
    build:
        docker:
            - image: circleci/node-nightwatch@latest
        working_directory: ~/repo
        steps:
            - checkout

            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "app/package-json" }}
            - run: npm i
            - run:
                name: lint
                working_directory: app
                command: |
                    npm run lint
            - run:
                name: test
                working_directory: app
                command: |
                    npm run e2e
