version: 2
jobs:
    build:
        docker:
            - image: karthikiyengar/node-nightwatch:latest
        working_directory: ~/repo
        steps:
            - checkout
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "app/package-json" }}
            - run: npm i
            - run: sudo npm i -g eslint eslint-config-standard eslint-friendly-formatter eslint-loader eslint-plugin-import eslint-plugin-node eslint-plugin-promise eslint-plugin-standard eslint-plugin-vue
            - run:
                name: lint
                working_directory: app
                command: |
                    npm run lint
            - run:
                name: test
                working_directory: app
                command: |
                    npm run e2e
