version: 2
jobs:
    build:
        docker:
            - image: circleci/node:latest
        working_directory: ~/tsuratsura
        steps:
            - checkout
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "app/package.json" }}
            - run:
                name: npm install
                working_directory: app
                command: npm i
            - run:
                name: lint
                working_directory: app
                command: |
                    npm run lint
            - run:
                name: test
                working_directory: app
                command: |
                    npm run e2e
