version: 2
jobs:
    build:
        docker:
            - image: circleci/node:11
        working_directory: ~/repo
        steps:
            - checkout

            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "app/package-json" }}
            - run:
            - run: echo "oracle-java8-installer shared/accepted-oracle-license-v1-1 boolean true" > debconf.txt
            - run: sudo debconf-set-selections debconf.txt
            - run: sudo apt-get install software-properties-common
            - run: sudo add-apt-repository "deb http://ppa.launchpad.net/webupd8team/java/ubuntu xenial main"
            - run: sudo apt-get update
            - run: sudo apt-get install oracle-java8-installer 
                name: test
                working_directory: app
                command: |
                    npm install
                    npm run lint
                    npm run e2e
