version: 2
jobs:
    build:
        docker:
            - image: circleci/node:11
        working_directory: ~/repo
        steps:
            - checkout

            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "app/package-json" }}
            - run: sudo apt install openjdk-11-jdk
            - run:
                name: test
                working_directory: app
                command: |
                    npm install
                    npm run lint
                    npm run e2e
