version: 2
jobs:
    build:
        docker:
            - image: circleci/node:11-browsers
        working_directory: ~/repo
        steps:
            - checkout

            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "app/package-json" }}
            - run: echo "deb http://http.debian.net/debian jessie-backports main" | sudo tee
            - run: sudo apt-get update
            - run: sudo apt-get install jessie-backports openjdk-8-jdk
            - run:
                name: test
                working_directory: app
                command: |
                    npm install
                    npm run lint
                    npm run e2e
