version: 2
jobs:
    build:
        docker:
            - image: circleci/node:11
        working_directory: ~/repo
        steps:
            - checkout

            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "app/package-json" }}
            - run: sudo add-apt-repository -y ppa:webupd8team/java; sudo apt-get update
            - run: echo "oracle-java9-installer shared/accepted-oracle-license-v1-1 select true" | sudo debconf-set-selections
            - run: echo "oracle-java9-installer shared/accepted-oracle-license-v1-1 seen true" | sudo debconf-set-selections
            - run: sudo apt-get -y install oracle-java9-installer
            - run: sudo apt-get install oracle-java9-set-default
            - run:
                name: test
                working_directory: app
                command: |
                    npm install
                    npm run lint
                    npm run e2e
