version: 2
jobs:
    build:
        docker:
            - image: circleci/node:11
        working_directory: ~/repo
        steps:
            - checkout

            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "app/package-json" }}
            - run:
                name: FrontCode lint
                working_directory: app
                command: |
                    npm install
<<<<<<< HEAD
=======
                    npm run lint
>>>>>>> abc737106d96a99cb9b9011a7c12d3614f12a75f

