version: 2
jobs:
    lint:
        docker:
            - image: circleci/node:11
        working_directory: ~/repo
        steps:
            - checkout

            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "app/package-json" }}
            - run:
                name: FrontCode lint
                working_directory: app
                command: |
                    npm install
                    npm run lint

    test_front:
        docker:
            - image: circleci/node:11
        working_directory: ~/repo
        steps:
            - checkout
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "app/package.json" }}

            - run:
                name: FrontCode test
                working_directory: app
                command: |
