version: 2
jobs:
    build:
        docker:
            - image: circleci/node:latest
        working_directory: ~/repo
        steps:
            - checkout
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "app/package-json" }}
            - run: npm i
            - run: sudo npm i -g eslint eslint-config-standard eslint-friendly-formatter eslint-loader eslint-plugin-import eslint-plugin-node eslint-plugin-promise eslint-plugin-standard eslint-plugin-vue babel-eslint
            - run:
                name: lint
                working_directory: app
                command: |
                    npm run lint
            - run: sudo npm i --save webpack webpack-bundle-analyzer webpack-dev-server webpack-merge extract-text-webpack-plugin eslint-friendly-formatter copy-webpack-plugin html-webpack-plugin optimize-css-assets-webpack-plugin friendly-errors-webpack-plugin uglifyjs-webpack-plugin
            - run:
                name: test
                working_directory: app
                command: |
                    npm run e2e
